#install docker
#sudo curl -sSL get.docker.com | sh

#pour les problemes de droit sur les répertoires : su -c "setenforce 0"

#arm
#FROM arm64v8/python
#FROM armhf/python
#FROM resin/rpi-raspbian:stretch
FROM hypriot/rpi-python

#docker build -t f80hub/material_matrix_arm . & docker push f80hub/material_matrix_arm:latest
#docker rm -f material_matrix && docker pull f80hub/material_matrix_arm:latest && docker run --restart=always -p 5000:5010 --name material_matrix -d f80hub/material_matrix_arm:latest



RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get dist-upgrade -y
RUN sudo apt-get install -y python3 python3-dev python3-pip python3-virtualenv --no-install-recommends && ln -s /usr/bin/python3 /usr/bin/python && rm -rf /var/lib/apt/lists/*


EXPOSE 5000

RUN mkdir /app
RUN mkdir /app/assets

WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY assets /app/assets

RUN pip3 install --upgrade pip
RUN pip3 install setuptools

RUN pip3 install -r requirements.txt

COPY . /app

ENTRYPOINT ["python", "app.py"]